name: reaktoro

{% set python_version = os.environ.get("PYTHON_VERSION", "3.10") %}

channels:
  - conda-forge

dependencies:
  - autodiff >=1.0.3
  - catch2 =2
  - ccache  # [unix]
  - clangxx_osx-64  # [osx]
  - cmake
  - cpp-tabulate
  - doxygen =1.9.1  # [linux]
  - eigen
  - fire
  - git
  - graphviz  # [linux]
  - gxx_linux-64  # [linux]
  - ipykernel                              # needed if using Jupyter Notebooks in Visual Studio Code
  - lld  # [unix]
  - make  # [unix]
  - matplotlib-base
  - nbformat                               # needed if using plotly in Jupyter Notebooks in Visual Studio Code
  - ninja
  - nlohmann_json
  - numpy
  - openlibm
  - optima >=0.3.3
  - pandas
  - phreeqc4rkt
  - pip
  - pybind11 >=2.10.0
  - pybind11-abi
  - pybind11-stubgen
  - pytest
  - pytest-regressions
  - pytest-xdist
  - python ={{ python_version }}
  - reaktplot >=0.4.1
  - thermofun =0.4.3
  - tsl_ordered_map
  - valgrind  # [unix]
  - vs2019_win-64  # [win]
  - yaml-cpp4rkt
  - pip:
    - oyaml
