#!/bin/bash

DIR=$(dirname $(readlink -f $0))
ROOT=$(readlink -f $DIR/..)
DOCS=$ROOT/docs

# Create some dirs
mkdir -p $DOCS/{css,js,fonts}
rm -rf $DOCS/css/* $DOCS/js/* $DOCS/fonts/*

# Update doxystrap stylesheet and javascript files
git clone --depth=1 git@bitbucket.org:allanleal/doxystrap.git tmp-doxystrap
cp tmp-doxystrap/*.css $DOCS/doxygen
cp tmp-doxystrap/*.js $DOCS/doxygen
rm -rf tmp-doxystrap

# Update bootstrap css and js
git clone --depth=1 https://github.com/twbs/bootstrap.git tmp-bootstrap
mv tmp-bootstrap/dist/js/bootstrap.min.js $DOCS/js/
cp tmp-bootstrap/dist/fonts/* $DOCS/fonts/
wget https://bootswatch.com/flatly/bootstrap.min.css -P $DOCS/css
rm -rf tmp-bootstrap

# Update highlight.js
wget https://highlightjs.org/download/ -P $DOCS/js

# Update font-awesome
git clone --depth=1 https://github.com/FortAwesome/Font-Awesome.git tmp-font-awesome
cp tmp-font-awesome/css/font-awesome.min.css $DOCS/css/
cp tmp-font-awesome/fonts/* $DOCS/fonts/
rm -rf tmp-font-awesome
