name: windows

on:
  push:
    branches:
      - main
      - master

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:
    name: ${{ matrix.config }} build on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        os: ["windows-2019"]
        python-version: [3.9]
        config: ["Release"]

    steps:
      - uses: actions/checkout@v3

      - name: Timestamp  # Idea from https://tinyurl.com/47wz7vpv
        id: timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=now::${current_date}")

      - name: Configuring Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\clcache
            C:\Users\runneradmin\conda_pkgs_dir
          key:
            ${{ runner.os }}-${{ matrix.config }}-${{ runner.python-version }}-${{ github.ref }}-clcache-${ { steps.timestamp.outputs.now } }
          restore-keys: |
            ${{ runner.os }}-${{ matrix.config }}-${{ runner.python-version }}-${{ github.ref }}-clcache-

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          allow-softlinks: true

      - name: Configuring Conda Environment
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          mamba install conda-devenv
          mamba devenv -e mamba

      - name: Building, Testing & Installing Reaktoro
        shell: cmd
        run: |
          call conda activate reaktoro || goto :eof
          clcache -s || goto :eof
          clcache -z || goto :eof
          mkdir .build && cd .build || goto :eof
          cmake -GNinja .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} || goto :eof
          ninja || goto :eof
          ninja install || goto :eof
          ninja tests || goto :eof
          ninja examples/install || goto :eof
          clcache -s || goto :eof
